[package]
name = "ball_in_a_box"
version = "1.0.0"
edition = "2021"

[dependencies]
circular-buffer = "0.1.9"
macroquad = { git = "https://github.com/KeMoonoDev/macroquad", rev = "2823897", features = [
    "audio",
] } # rev from branch "ball-in-a-box"
nanoserde = { git = "https://github.com/KeMoonoDev/nanoserde", rev = "6e42d4c" } # rev from branch "ball-in-a-box"
quad-rand = "0.2.2"

[build-dependencies]
image = { version = "0.24", default-features = false, features = [
    "png",
    "ico",
] }
winresource = { version = "0.1.19", default-features = false }

[patch.crates-io]
miniquad = { git = "https://github.com/KeMoonoDev/miniquad", rev = "34122a6" } # rev from branch "ball-in-a-box"

[profile.release]
opt-level = 'z'
codegen-units = 1
panic = "abort"
lto = true
strip = true
debug-assertions = false
overflow-checks = false
